export const metadata = {
  title: 'Login',
  description: 'Generated by Next.js',
}

export default function LoginLayout({
  children,
}: {
  children: React.ReactNode
}) {
    return (
        <main className='flex flex-col h-screen bg-[#252525]'>
          {children}
        </main>
    )
}
