export const metadata = {
  title: 'Sign up',
  description: 'Generated by Next.js',
}

const signupLayout = ({
  children,
}: {
  children: React.ReactNode
}) => {
    return (
        <main className='flex flex-col h-screen bg-[#252525]'>{children}</main>
    );
}

export default signupLayout;